#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["httpx>=0.27"]
# ///
"""issue-watch.py — track new GitHub issues across vendored upstream Zscaler repos.

Status: functional.

Walks the seven vendored upstream repos via the public GitHub REST API. Compares
against last-seen timestamps per repo (saved to logs/issue-watch-state.json).
Outputs new and updated issues to logs/issues-new.md for human triage.

Run:
    ./scripts/issue-watch.py

First run: fetches issues updated in the last 30 days (configurable via
FIRST_RUN_LOOKBACK_DAYS). Subsequent runs fetch only what's new since the
previous run's timestamp.

Authentication:
    Public repos work unauthenticated at 60 requests/hr per IP — sufficient
    for the seven repos checked weekly. For higher rate limits, set
    GITHUB_TOKEN in the environment.

Manual review workflow:
    1. Run script.
    2. Open logs/issues-new.md.
    3. For each surfaced issue, eyeball: does it touch documented skill behavior?
       - Yes → source-check + thread per references/_verification-protocol.md.
       - Schema drift in TF / SDK → re-run scripts/find-asymmetries.py.
       - No bearing on skill → skip.
    4. Re-run weekly (or after a submodule bump catches you up).

The state file tracks per-repo last-fetch timestamps. Both state and output live
in logs/ (gitignored upstream — populated per-fork).
"""

import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import httpx

REPO_ROOT = Path(__file__).resolve().parent.parent
STATE_FILE = REPO_ROOT / "logs" / "issue-watch-state.json"
OUTPUT = REPO_ROOT / "logs" / "issues-new.md"

REPOS = [
    "zscaler/zscaler-sdk-python",
    "zscaler/zscaler-sdk-go",
    "zscaler/terraform-provider-zia",
    "zscaler/terraform-provider-zpa",
    "zscaler/terraform-provider-ztc",
    "zscaler/zscaler-mcp-server",
    "zscaler/zscaler-api-specs",
]

GITHUB_API = "https://api.github.com"
FIRST_RUN_LOOKBACK_DAYS = 30


def load_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except json.JSONDecodeError:
            print(f"WARN: {STATE_FILE} unparseable; treating as empty state", file=sys.stderr)
    return {}


def save_state(state: dict):
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2, sort_keys=True))


def fetch_issues(client: httpx.Client, repo: str, since: str) -> list[dict]:
    """Fetch issues updated since the given ISO timestamp. Returns a list of issue
    dicts (with PRs filtered out — GitHub's /issues endpoint includes them by default)."""
    issues = []
    page = 1
    while True:
        params = {
            "state": "all",
            "per_page": "100",
            "page": str(page),
            "since": since,
            "sort": "updated",
            "direction": "desc",
        }
        r = client.get(f"{GITHUB_API}/repos/{repo}/issues", params=params)
        r.raise_for_status()
        batch = r.json()
        if not batch:
            break
        # Filter out PRs (the issues endpoint conflates issues + PRs)
        issues.extend(i for i in batch if "pull_request" not in i)
        if len(batch) < 100:
            break
        page += 1
        if page > 10:
            # Safety: cap at 1000 issues per repo per run
            print(f"WARN: hit page cap on {repo}; truncating", file=sys.stderr)
            break
    return issues


def render_report(new_issues: list[dict], previous_state: dict, current_run_at: str) -> str:
    by_repo: dict[str, list[dict]] = {}
    for issue in new_issues:
        by_repo.setdefault(issue["_repo"], []).append(issue)

    lines = [
        "# New / updated GitHub issues across vendored upstream repos",
        "",
        f"Generated by `scripts/issue-watch.py` at {current_run_at}.",
        "",
        f"- Repos checked: {len(REPOS)}",
        f"- New / updated issues since last run: {len(new_issues)}",
        "",
        "Triage workflow:",
        "",
        "1. Each issue below is a candidate. Read the title; click through if it looks behavioral.",
        "2. Issues that touch documented skill behavior → source-check + thread per "
        "[`references/_verification-protocol.md`](../references/_verification-protocol.md).",
        "3. Issues that look like TF schema drift or SDK enum changes → re-run "
        "`scripts/find-asymmetries.py`.",
        "4. Issues that don't bear on the skill → skip.",
        "",
        "---",
        "",
    ]

    if not new_issues:
        lines.append("**No new or updated issues since last run.**")
        return "\n".join(lines)

    for repo in REPOS:
        issues = by_repo.get(repo, [])
        if not issues:
            continue
        last_seen = previous_state.get(repo, "never")
        lines.append(f"## {repo} ({len(issues)})")
        lines.append("")
        lines.append(f"*Last checked: {last_seen[:19] if last_seen != 'never' else 'never'}*")
        lines.append("")
        for issue in sorted(issues, key=lambda i: -int(i["number"])):
            state_icon = "🟢 open" if issue["state"] == "open" else "🔴 closed"
            labels = ", ".join(l["name"] for l in issue.get("labels", []))
            label_str = f" [{labels}]" if labels else ""
            comment_count = issue.get("comments", 0)
            comment_str = f" ({comment_count} comments)" if comment_count else ""
            lines.append(
                f"- {state_icon} [#{issue['number']}]({issue['html_url']}) — "
                f"{issue['title']}{label_str}{comment_str}  "
                f"*(updated {issue['updated_at'][:10]})*"
            )
        lines.append("")

    return "\n".join(lines)


def main():
    state = load_state()
    headers = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}
    if token := os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {token}"
        print("Using GITHUB_TOKEN for authentication (5000 req/hr)", file=sys.stderr)
    else:
        print("Running unauthenticated (60 req/hr per IP)", file=sys.stderr)

    default_since = (
        datetime.now(timezone.utc) - timedelta(days=FIRST_RUN_LOOKBACK_DAYS)
    ).isoformat()
    new_issues = []
    new_state = {}
    current_run_at = datetime.now(timezone.utc).isoformat()

    with httpx.Client(headers=headers, timeout=30.0) as client:
        for repo in REPOS:
            since = state.get(repo, default_since)
            print(f"Checking {repo} (since {since[:19]})...", file=sys.stderr)
            try:
                issues = fetch_issues(client, repo, since)
            except httpx.HTTPStatusError as e:
                msg = e.response.text[:200] if e.response else str(e)
                print(f"  ERROR {e.response.status_code if e.response else '?'}: {msg}", file=sys.stderr)
                # Carry over previous state so we re-attempt next run
                new_state[repo] = state.get(repo)
                continue
            except httpx.HTTPError as e:
                print(f"  HTTP ERROR: {e}", file=sys.stderr)
                new_state[repo] = state.get(repo)
                continue
            for i in issues:
                i["_repo"] = repo
            new_issues.extend(issues)
            print(f"  Found {len(issues)} issues", file=sys.stderr)
            new_state[repo] = current_run_at

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render_report(new_issues, state, current_run_at))
    save_state(new_state)

    print(f"Wrote {OUTPUT}")
    print(f"  {len(new_issues)} new / updated issues across {len(REPOS)} repos")


if __name__ == "__main__":
    main()
